# -*- coding: utf-8 -*-

# LogPage implementation generated from reading ui file 'UI_LogPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogPage(object):
    def setupUi(self, LogPage):
        LogPage.setObjectName("LogPage")
        LogPage.resize(639, 440)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(LogPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.clearButton = QtWidgets.QPushButton(LogPage)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LogPage)
        QtCore.QMetaObject.connectSlotsByName(LogPage)

    def retranslateUi(self, LogPage):
        _translate = QtCore.QCoreApplication.translate
        LogPage.setWindowTitle(_translate("LogPage", "LogPage"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("LogPage", "发生时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("LogPage", "提示信息"))
        self.clearButton.setText(_translate("LogPage", "清除"))
