# -*- coding: utf-8 -*-

# LogPage implementation generated from reading ui file 'UI_LogPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogPage(object):
    def setupUi(self, LogPage):
        LogPage.setObjectName("LogPage")
        LogPage.resize(639, 440)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(LogPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.flashButton = QtWidgets.QPushButton(LogPage)
        self.flashButton.setObjectName("flashButton")
        self.horizontalLayout.addWidget(self.flashButton)
        self.clearButton = QtWidgets.QPushButton(LogPage)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LogPage)
        QtCore.QMetaObject.connectSlotsByName(LogPage)

    def retranslateUi(self, LogPage):
        _translate = QtCore.QCoreApplication.translate
        LogPage.setWindowTitle(_translate("LogPage", "LogPage"))
        self.flashButton.setText(_translate("LogPage", "刷新"))
        self.clearButton.setText(_translate("LogPage", "清除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogPage = QtWidgets.QWidget()
    ui = Ui_LogPage()
    ui.setupUi(LogPage)
    LogPage.show()
    sys.exit(app.exec_())
