# -*- coding: utf-8 -*-

# ModelManagePage implementation generated from reading ui file 'UI_ModelManagePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelManagePage(object):
    def setupUi(self, ModelManagePage):
        ModelManagePage.setObjectName("ModelManagePage")
        ModelManagePage.resize(633, 444)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModelManagePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(ModelManagePage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(ModelManagePage)
        QtCore.QMetaObject.connectSlotsByName(ModelManagePage)

    def retranslateUi(self, ModelManagePage):
        _translate = QtCore.QCoreApplication.translate
        ModelManagePage.setWindowTitle(_translate("ModelManagePage", "ModelManagePage"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ModelManagePage", "模型名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ModelManagePage", "预训练模型"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ModelManagePage", "备注"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ModelManagePage", "状态"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ModelManagePage", "操作"))
