# -*- coding: utf-8 -*-

# TaskPage implementation generated from reading ui file 'UI_TaskPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskPage(object):
    def setupUi(self, TaskPage):
        TaskPage.setObjectName("TaskPage")
        TaskPage.resize(781, 473)
        self.verticalLayout = QtWidgets.QVBoxLayout(TaskPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(TaskPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_Button = QtWidgets.QPushButton(TaskPage)
        self.select_Button.setObjectName("select_Button")
        self.horizontalLayout.addWidget(self.select_Button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.confirm_Button = QtWidgets.QPushButton(TaskPage)
        self.confirm_Button.setObjectName("confirm_Button")
        self.horizontalLayout.addWidget(self.confirm_Button)
        self.delete_Button = QtWidgets.QPushButton(TaskPage)
        self.delete_Button.setObjectName("delete_Button")
        self.horizontalLayout.addWidget(self.delete_Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TaskPage)
        QtCore.QMetaObject.connectSlotsByName(TaskPage)

    def retranslateUi(self, TaskPage):
        _translate = QtCore.QCoreApplication.translate
        TaskPage.setWindowTitle(_translate("TaskPage", "TaskPage"))
        #self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TaskPage", "生产线"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TaskPage", "任务标识符"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TaskPage", "产品名称"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TaskPage", "批号"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TaskPage", "物料类型"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TaskPage", "检测数量"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TaskPage", "识别类型"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("TaskPage", "是否完成"))
        self.select_Button.setText(_translate("TaskPage", "模型选择"))
        self.confirm_Button.setText(_translate("TaskPage", "确认"))
        self.delete_Button.setText(_translate("TaskPage", "删除"))
