# -*- coding: utf-8 -*-

# TaskPage implementation generated from reading ui file 'UI_TaskPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskPage(object):
    def setupUi(self, TaskPage):
        TaskPage.setObjectName("TaskPage")
        TaskPage.resize(866, 530)
        self.verticalLayout = QtWidgets.QVBoxLayout(TaskPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(TaskPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(TaskPage)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(TaskPage)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TaskPage)
        QtCore.QMetaObject.connectSlotsByName(TaskPage)

    def retranslateUi(self, TaskPage):
        _translate = QtCore.QCoreApplication.translate
        TaskPage.setWindowTitle(_translate("TaskPage", "TaskPage"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TaskPage", "任务序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TaskPage", "批号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TaskPage", "物料类型"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TaskPage", "产品物料名称"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TaskPage", "生产日期"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TaskPage", "有效期至"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TaskPage", "产线"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("TaskPage", "检测数量"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("TaskPage", "是否完成"))
        self.pushButton.setText(_translate("TaskPage", "确认"))
        self.pushButton_2.setText(_translate("TaskPage", "删除"))
