# -*- coding: utf-8 -*-

# UsersPage implementation generated from reading ui file 'UI_UsersPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UsersPage(object):
    def setupUi(self, UsersPage):
        UsersPage.setObjectName("UsersPage")
        UsersPage.resize(611, 397)
        self.verticalLayout = QtWidgets.QVBoxLayout(UsersPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(UsersPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addButton = QtWidgets.QPushButton(UsersPage)
        self.addButton.setMinimumSize(QtCore.QSize(50, 40))
        self.addButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(UsersPage)
        QtCore.QMetaObject.connectSlotsByName(UsersPage)

    def retranslateUi(self, UsersPage):
        _translate = QtCore.QCoreApplication.translate
        UsersPage.setWindowTitle(_translate("UsersPage", "UsersPage"))
        self.addButton.setText(_translate("UsersPage", "新增用户"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UsersPage = QtWidgets.QWidget()
    ui = Ui_UsersPage()
    ui.setupUi(UsersPage)
    UsersPage.show()
    sys.exit(app.exec_())
